/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 RI_TemplateScene.gltf --transform --keepnames 
Files: RI_TemplateScene.gltf [4.18MB] > /Users/hgs52/Documents/GitHub/RI-Map-R3F/my-app/public/RI_TemplateScene-transformed.glb [7.77MB] (-86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/RI_TemplateScene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group name="baum_ld1_mobile_(10)" position={[-144.472, 19.139, 481.984]} scale={1.444}>
        <mesh name="baum_ld1_mobile_(10)_1" geometry={nodes['baum_ld1_mobile_(10)_1'].geometry} material={materials['ast4 lw']} />
        <mesh name="baum_ld1_mobile_(10)_2" geometry={nodes['baum_ld1_mobile_(10)_2'].geometry} material={materials.Bark} />
      </group>
      <mesh name="baum_ld2_mobile_(4)" geometry={nodes['baum_ld2_mobile_(4)'].geometry} material={materials['ast5 lw']} position={[-856.334, 17.014, 1292.63]} scale={2.058} />
      <mesh name="baum_ld0_mobile_(5)" geometry={nodes['baum_ld0_mobile_(5)'].geometry} material={materials['ast3 lw']} position={[-809.535, 17.2, 1244.02]} scale={2.058} />
      <group name="Mesh1" position={[-292.325, 18.11, 809]} rotation={[-Math.PI, 0.213, -Math.PI]} scale={82.32}>
        <mesh name="Mesh1_2" geometry={nodes.Mesh1_2.geometry} material={materials.F_rgen_10} />
        <mesh name="Mesh1_3" geometry={nodes.Mesh1_3.geometry} material={materials.F_rgen_1} />
        <mesh name="Mesh1_4" geometry={nodes.Mesh1_4.geometry} material={materials.MF_20R_1} />
        <mesh name="Mesh1_5" geometry={nodes.Mesh1_5.geometry} material={materials.MF_20R_1_4} />
        <mesh name="Mesh1_6" geometry={nodes.Mesh1_6.geometry} material={materials.F_rgen_5} />
        <mesh name="Mesh1_7" geometry={nodes.Mesh1_7.geometry} material={materials.F_rgen_7} />
        <mesh name="Mesh1_8" geometry={nodes.Mesh1_8.geometry} material={materials.F_rgen_2} />
        <mesh name="Mesh1_9" geometry={nodes.Mesh1_9.geometry} material={materials.F_rgen_1_1} />
        <mesh name="Mesh1_10" geometry={nodes.Mesh1_10.geometry} material={materials.F_rgen_9} />
        <mesh name="Mesh1_11" geometry={nodes.Mesh1_11.geometry} material={materials.F_rgen_6} />
        <mesh name="Mesh1_12" geometry={nodes.Mesh1_12.geometry} material={materials.MF_20R_1_1} />
        <mesh name="Mesh1_13" geometry={nodes.Mesh1_13.geometry} material={materials.MF_20R_1_2} />
        <mesh name="Mesh1_14" geometry={nodes.Mesh1_14.geometry} material={materials.F_rgen_3} />
        <mesh name="Mesh1_15" geometry={nodes.Mesh1_15.geometry} material={materials.MF_20R_1_2_1} />
        <mesh name="Mesh1_16" geometry={nodes.Mesh1_16.geometry} material={materials.MF_20R_1_3} />
        <mesh name="Mesh1_17" geometry={nodes.Mesh1_17.geometry} material={materials.F_rged_k_3} />
        <mesh name="Mesh1_18" geometry={nodes.Mesh1_18.geometry} material={materials.F_rgen_51} />
        <mesh name="Mesh1_19" geometry={nodes.Mesh1_19.geometry} material={materials.F_rgen_53} />
        <mesh name="Mesh1_20" geometry={nodes.Mesh1_20.geometry} material={materials.F_rgen_1_4} />
        <mesh name="Mesh1_21" geometry={nodes.Mesh1_21.geometry} material={materials.MF_20R_1_4_5} />
        <mesh name="Mesh1_22" geometry={nodes.Mesh1_22.geometry} material={materials.MF_20R_1_3_1} />
        <mesh name="Mesh1_23" geometry={nodes.Mesh1_23.geometry} material={materials.MF_20R_1_5} />
        <mesh name="Mesh1_24" geometry={nodes.Mesh1_24.geometry} material={materials.PaletteMaterial001} />
        <mesh name="Mesh1_25" geometry={nodes.Mesh1_25.geometry} material={materials.F_rgen_1_2} />
        <mesh name="Mesh1_26" geometry={nodes.Mesh1_26.geometry} material={materials.F_rgen_1_3} />
      </group>
      <mesh name="Mercedes-Benz_E63_(1)" geometry={nodes['Mercedes-Benz_E63_(1)'].geometry} material={materials.PaletteMaterial002} position={[-595.009, 18.28, 1099.61]} rotation={[0.001, -0.594, 0.001]} scale={0.031} />
      <mesh name="Stop_(1)" geometry={nodes['Stop_(1)'].geometry} material={materials.M_Stop} position={[14.865, 21.309, 65.638]} rotation={[Math.PI / 2, 0, -2.182]} scale={0.072} />
      <mesh name="Object_1" geometry={nodes.Object_1.geometry} material={materials.Railing} position={[-34.163, -276.163, 353.153]} scale={100.073} />
      <mesh name="Mesh18_3" geometry={nodes.Mesh18_3.geometry} material={materials.End1} position={[-34.163, -276.163, 353.153]} scale={100.073} />
      <mesh name="Mesh18_2" geometry={nodes.Mesh18_2.geometry} material={materials.End2} position={[-34.163, -276.163, 353.153]} scale={100.073} />
      <mesh name="Mesh18" geometry={nodes.Mesh18.geometry} material={materials._Brick_Antique_01_1} position={[-34.163, -276.163, 353.153]} scale={100.073} />
      <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.T_Store1} position={[-34.163, -275.937, 352.947]} scale={100.073} />
      <mesh name="Object_1_1" geometry={nodes.Object_1_1.geometry} material={materials.T_Store2} position={[-34.163, -275.937, 352.947]} scale={100.073} />
      <mesh name="Object_1_2" geometry={nodes.Object_1_2.geometry} material={materials.Cinder_Block} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.StoreFront} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh183_2" geometry={nodes.Mesh183_2.geometry} material={materials._17} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh22" geometry={nodes.Mesh22.geometry} material={materials.T_Library2} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh22_2" geometry={nodes.Mesh22_2.geometry} material={materials.T_Library1} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh22_7" geometry={nodes.Mesh22_7.geometry} material={materials._Polished_Concrete_New_1} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh22_8" geometry={nodes.Mesh22_8.geometry} material={materials.M_531c} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh9_5" geometry={nodes.Mesh9_5.geometry} material={materials.T_B1} position={[-34.163, -277.835, 352.947]} scale={100.073} />
      <mesh name="Mesh19_5" geometry={nodes.Mesh19_5.geometry} material={materials.T_B2} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh17_4" geometry={nodes.Mesh17_4.geometry} material={materials.T_B4} position={[-34.163, -277.035, 352.947]} scale={100.073} />
      <mesh name="Mesh17_7" geometry={nodes.Mesh17_7.geometry} material={materials.T_B3} position={[-34.163, -277.035, 352.947]} scale={100.073} />
      <mesh name="Mesh2" geometry={nodes.Mesh2.geometry} material={materials.Fencing_Construction} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh186_41" geometry={nodes.Mesh186_41.geometry} material={materials.Roofing_Shingles_Asphalt} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh613" geometry={nodes.Mesh613.geometry} material={materials._Vegetation_Grass_1} position={[-34.163, -275.834, 352.947]} scale={100.073} />
      <mesh name="Mesh17_6" geometry={nodes.Mesh17_6.geometry} material={materials._Brick_Antique_01_1} position={[-34.163, -277.035, 352.947]} scale={100.073} />
      <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.Blinds_Roman_Hobbled_Blue} position={[-34.163, -277.035, 352.947]} scale={100.073} />
      <mesh name="Object_1_3" geometry={nodes.Object_1_3.geometry} material={materials.Wood_bench} position={[-34.163, -276.163, 352.947]} scale={100.073} />
      <mesh name="Object_2_1" geometry={nodes.Object_2_1.geometry} material={materials['Custom (2)']} position={[-34.163, -276.163, 352.947]} scale={100.073} />
      <mesh name="Mesh603" geometry={nodes.Mesh603.geometry} material={materials.M_510A} position={[-34.163, -276.163, 352.947]} scale={100.073} />
      <mesh name="Mesh603_2" geometry={nodes.Mesh603_2.geometry} material={materials.M_510C} position={[-34.163, -276.163, 352.947]} scale={100.073} />
      <mesh name="Mesh603_3" geometry={nodes.Mesh603_3.geometry} material={materials.M_510D} position={[-34.163, -276.163, 352.947]} scale={100.073} />
      <mesh name="Mesh604_6" geometry={nodes.Mesh604_6.geometry} material={materials.M_510B} position={[-34.163, -276.163, 352.947]} scale={100.073} />
      <mesh name="Object_1_4" geometry={nodes.Object_1_4.geometry} material={materials['Custom (1)']} position={[-34.163, -275.937, 352.947]} scale={100.073} />
      <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.Polished_Concrete_Old} position={[-34.163, -275.937, 352.947]} scale={100.073} />
      <mesh name="Mesh375_3" geometry={nodes.Mesh375_3.geometry} material={materials.bricks_zigzag_texture_6190218_1_1} position={[-34.163, -275.937, 352.947]} scale={100.073} />
      <mesh name="Mesh89" geometry={nodes.Mesh89.geometry} material={materials.Fencing_Chain_Link} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh189" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh189_1" geometry={nodes.Mesh189_1.geometry} material={materials.Stone_01} />
        <mesh name="Mesh189_2" geometry={nodes.Mesh189_2.geometry} material={materials.Ground_HD_01} />
      </group>
      <mesh name="Mesh292" geometry={nodes.Mesh292.geometry} material={materials.M_166683_143419735717653_3129085_n} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh293" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh293_1" geometry={nodes.Mesh293_1.geometry} material={materials.DSC00022_2} />
        <mesh name="Mesh293_2" geometry={nodes.Mesh293_2.geometry} material={materials._71} />
        <mesh name="Mesh293_3" geometry={nodes.Mesh293_3.geometry} material={materials.Image10} />
        <mesh name="Mesh293_4" geometry={nodes.Mesh293_4.geometry} material={materials.Image} />
        <mesh name="Mesh293_5" geometry={nodes.Mesh293_5.geometry} material={materials._72} />
      </group>
      <group name="Mesh294" position={[-42.179, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh294_2" geometry={nodes.Mesh294_2.geometry} material={materials.SV_Hochhaus_by_Sebastian_S_1} />
        <mesh name="Mesh294_3" geometry={nodes.Mesh294_3.geometry} material={materials.Translucent_Resin_Crush_Gray} />
      </group>
      <mesh name="Mesh628" geometry={nodes.Mesh628.geometry} material={materials.Groundcover_Sand_Smooth} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh629" geometry={nodes.Mesh629.geometry} material={materials.Vegetation_Grass1} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh412" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh412_1" geometry={nodes.Mesh412_1.geometry} material={materials.v} />
        <mesh name="Mesh412_2" geometry={nodes.Mesh412_2.geometry} material={materials.s1} />
        <mesh name="Mesh412_3" geometry={nodes.Mesh412_3.geometry} material={materials.s2} />
        <mesh name="Mesh412_4" geometry={nodes.Mesh412_4.geometry} material={materials.h} />
        <mesh name="Mesh412_5" geometry={nodes.Mesh412_5.geometry} material={materials.h1} />
        <mesh name="Mesh412_6" geometry={nodes.Mesh412_6.geometry} material={materials.v1} />
        <mesh name="Mesh412_7" geometry={nodes.Mesh412_7.geometry} material={materials.v2} />
        <mesh name="Mesh412_8" geometry={nodes.Mesh412_8.geometry} material={materials.v3} />
        <mesh name="Mesh412_9" geometry={nodes.Mesh412_9.geometry} material={materials.s3} />
        <mesh name="Mesh412_10" geometry={nodes.Mesh412_10.geometry} material={materials.s4} />
        <mesh name="Mesh412_11" geometry={nodes.Mesh412_11.geometry} material={materials.s5} />
        <mesh name="Mesh412_12" geometry={nodes.Mesh412_12.geometry} material={materials.jjk} />
        <mesh name="Mesh412_13" geometry={nodes.Mesh412_13.geometry} material={materials.v4} />
        <mesh name="Mesh412_14" geometry={nodes.Mesh412_14.geometry} material={materials.v5} />
        <mesh name="Mesh412_15" geometry={nodes.Mesh412_15.geometry} material={materials.v6} />
        <mesh name="Mesh412_16" geometry={nodes.Mesh412_16.geometry} material={materials.v7} />
        <mesh name="Mesh412_17" geometry={nodes.Mesh412_17.geometry} material={materials.v8} />
        <mesh name="Mesh412_18" geometry={nodes.Mesh412_18.geometry} material={materials.v9} />
        <mesh name="Mesh412_19" geometry={nodes.Mesh412_19.geometry} material={materials.s} />
      </group>
      <mesh name="Mesh190" geometry={nodes.Mesh190.geometry} material={materials.Metal_Steel_Textured} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh80" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh80_1" geometry={nodes.Mesh80_1.geometry} material={materials.the_house_1} />
        <mesh name="Mesh80_2" geometry={nodes.Mesh80_2.geometry} material={materials.the_house_TILE1} />
      </group>
      <mesh name="Mesh81" geometry={nodes.Mesh81.geometry} material={materials.Polished_Concrete_Old} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh83" position={[-42.189, 1.441, -37.034]} scale={1.001}>
        <mesh name="Mesh83_1" geometry={nodes.Mesh83_1.geometry} material={materials.M_179631_143679609024999_2226710_n} />
        <mesh name="Mesh83_2" geometry={nodes.Mesh83_2.geometry} material={materials.Granite_Light_Gray} />
      </group>
      <mesh name="Mesh617" geometry={nodes.Mesh617.geometry} material={materials.M_167326_143444519048508_363337_n1} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh298" geometry={nodes.Mesh298.geometry} material={materials.M_168015_143418109051149_4438621_n2} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh304" geometry={nodes.Mesh304.geometry} material={materials.M_164300_143443922381901_4659392_n} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh314" geometry={nodes.Mesh314.geometry} material={materials.M_166887_143444205715206_6382098_n1} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh52" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh52_1" geometry={nodes.Mesh52_1.geometry} material={materials.verizon2} />
        <mesh name="Mesh52_2" geometry={nodes.Mesh52_2.geometry} material={materials.Concrete_Form_4x8} />
        <mesh name="Mesh52_3" geometry={nodes.Mesh52_3.geometry} material={materials.M_168015_143418109051149_4438621_n} />
      </group>
      <mesh name="Mesh54" geometry={nodes.Mesh54.geometry} material={materials.verizon3} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh41" geometry={nodes.Mesh41.geometry} material={materials.Image9} position={[-42.189, 0.44, -37.044]} scale={1.001} />
      <group name="Mesh25" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh25_4" geometry={nodes.Mesh25_4.geometry} material={materials.C_pia__6__de_14609120} />
        <mesh name="Mesh25_5" geometry={nodes.Mesh25_5.geometry} material={materials.C_pia__7__de_14609120} />
        <mesh name="Mesh25_6" geometry={nodes.Mesh25_6.geometry} material={materials.C_pia__3__de_14609120} />
        <mesh name="Mesh25_7" geometry={nodes.Mesh25_7.geometry} material={materials.C_pia__5__de_1} />
        <mesh name="Mesh25_8" geometry={nodes.Mesh25_8.geometry} material={materials.C_pia__5__de_14609120} />
        <mesh name="Mesh25_9" geometry={nodes.Mesh25_9.geometry} material={materials.C_pia_de_14609120} />
        <mesh name="Mesh25_10" geometry={nodes.Mesh25_10.geometry} material={materials.C_pia__4__de_14609120_c_pia} />
        <mesh name="Mesh25_11" geometry={nodes.Mesh25_11.geometry} material={materials.C_pia__2__de_1} />
        <mesh name="Mesh25_12" geometry={nodes.Mesh25_12.geometry} material={materials.C_pia__3__de_1} />
        <mesh name="Mesh25_13" geometry={nodes.Mesh25_13.geometry} material={materials.C_pia__4__de_14609120} />
        <mesh name="Mesh25_14" geometry={nodes.Mesh25_14.geometry} material={materials.C_pia__3__de_3439380_c_pia} />
        <mesh name="Mesh25_15" geometry={nodes.Mesh25_15.geometry} material={materials.C_pia_de_2} />
        <mesh name="Mesh25_16" geometry={nodes.Mesh25_16.geometry} material={materials.C_pia__4__de_1} />
        <mesh name="Mesh25_17" geometry={nodes.Mesh25_17.geometry} material={materials.C_pia__3__de_14609120_c_pia} />
        <mesh name="Mesh25_18" geometry={nodes.Mesh25_18.geometry} material={materials.C_pia_de_14609120_c_pia_c_pia} />
        <mesh name="Mesh25_19" geometry={nodes.Mesh25_19.geometry} material={materials.C_pia__2__de_3439380} />
        <mesh name="Mesh25_20" geometry={nodes.Mesh25_20.geometry} material={materials.C_pia__2__de_3439380_c_pia1} />
        <mesh name="Mesh25_21" geometry={nodes.Mesh25_21.geometry} material={materials.C_pia_de_1} />
        <mesh name="Mesh25_22" geometry={nodes.Mesh25_22.geometry} material={materials.C_pia__2__de_14609120} />
        <mesh name="Mesh25_23" geometry={nodes.Mesh25_23.geometry} material={materials.C_pia_de_14609120_c_pia} />
        <mesh name="Mesh25_24" geometry={nodes.Mesh25_24.geometry} material={materials.esq} />
        <mesh name="Mesh25_25" geometry={nodes.Mesh25_25.geometry} material={materials.bjkl_vjljhvhg_c_pia} />
      </group>
      <mesh name="Mesh11" geometry={nodes.Mesh11.geometry} material={materials.M_4thSmallHouseSW} position={[-42.189, 0.44, -37.044]} scale={1.001} />
      <mesh name="Mesh86" geometry={nodes.Mesh86.geometry} material={materials.M_179676_143445665715060_6114280_n} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh88" geometry={nodes.Mesh88.geometry} material={materials.M_180174_143434342382859_3170241_n1} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh5" geometry={nodes.Mesh5.geometry} material={materials.Cladding_Siding_White} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh10" geometry={nodes.Mesh10.geometry} material={materials.Image1} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh319" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh319_1" geometry={nodes.Mesh319_1.geometry} material={materials.M_32} />
        <mesh name="Mesh319_2" geometry={nodes.Mesh319_2.geometry} material={materials.Image5} />
        <mesh name="Mesh319_3" geometry={nodes.Mesh319_3.geometry} material={materials.Image6} />
      </group>
      <mesh name="Mesh4" geometry={nodes.Mesh4.geometry} material={materials.M_480} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh619" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh619_1" geometry={nodes.Mesh619_1.geometry} material={materials.Image12} />
        <mesh name="Mesh619_2" geometry={nodes.Mesh619_2.geometry} material={materials.M_531A} />
        <mesh name="Mesh619_3" geometry={nodes.Mesh619_3.geometry} material={materials.M_531b} />
        <mesh name="Mesh619_4" geometry={nodes.Mesh619_4.geometry} material={materials.M_510} />
      </group>
      <group name="Mesh315" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh315_1" geometry={nodes.Mesh315_1.geometry} material={materials.__4} />
        <mesh name="Mesh315_2" geometry={nodes.Mesh315_2.geometry} material={materials.__8} />
      </group>
      <group name="Mesh316" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh316_1" geometry={nodes.Mesh316_1.geometry} material={materials.M_164337_143414945718132_5431013_n1} />
        <mesh name="Mesh316_2" geometry={nodes.Mesh316_2.geometry} material={materials.M_888B1_1} />
        <mesh name="Mesh316_3" geometry={nodes.Mesh316_3.geometry} material={materials.M_888B1_2} />
        <mesh name="Mesh316_4" geometry={nodes.Mesh316_4.geometry} material={materials.M_180458_143433712382922_550257_n} />
        <mesh name="Mesh316_5" geometry={nodes.Mesh316_5.geometry} material={materials.M_888B1_3} />
        <mesh name="Mesh316_6" geometry={nodes.Mesh316_6.geometry} material={materials.M_888B1_4} />
        <mesh name="Mesh316_7" geometry={nodes.Mesh316_7.geometry} material={materials.M_888B1} />
      </group>
      <group name="Mesh36" position={[-42.189, 12.849, -37.044]} scale={1.001}>
        <mesh name="Mesh36_1" geometry={nodes.Mesh36_1.geometry} material={materials._16} />
        <mesh name="Mesh36_2" geometry={nodes.Mesh36_2.geometry} material={materials._13} />
        <mesh name="Mesh36_3" geometry={nodes.Mesh36_3.geometry} material={materials._18} />
        <mesh name="Mesh36_4" geometry={nodes.Mesh36_4.geometry} material={materials._12} />
        <mesh name="Mesh36_5" geometry={nodes.Mesh36_5.geometry} material={materials._7} />
        <mesh name="Mesh36_6" geometry={nodes.Mesh36_6.geometry} material={materials._11} />
        <mesh name="Mesh36_7" geometry={nodes.Mesh36_7.geometry} material={materials._8} />
        <mesh name="Mesh36_8" geometry={nodes.Mesh36_8.geometry} material={materials._9} />
        <mesh name="Mesh36_9" geometry={nodes.Mesh36_9.geometry} material={materials._29} />
        <mesh name="Mesh36_10" geometry={nodes.Mesh36_10.geometry} material={materials._28} />
        <mesh name="Mesh36_11" geometry={nodes.Mesh36_11.geometry} material={materials._6} />
        <mesh name="Mesh36_12" geometry={nodes.Mesh36_12.geometry} material={materials._30} />
        <mesh name="Mesh36_13" geometry={nodes.Mesh36_13.geometry} material={materials._20} />
        <mesh name="Mesh36_14" geometry={nodes.Mesh36_14.geometry} material={materials._33} />
        <mesh name="Mesh36_15" geometry={nodes.Mesh36_15.geometry} material={materials._32} />
        <mesh name="Mesh36_16" geometry={nodes.Mesh36_16.geometry} material={materials._36} />
        <mesh name="Mesh36_17" geometry={nodes.Mesh36_17.geometry} material={materials._4} />
        <mesh name="Mesh36_18" geometry={nodes.Mesh36_18.geometry} material={materials._3} />
        <mesh name="Mesh36_19" geometry={nodes.Mesh36_19.geometry} material={materials._15} />
        <mesh name="Mesh36_20" geometry={nodes.Mesh36_20.geometry} material={materials._21} />
        <mesh name="Mesh36_21" geometry={nodes.Mesh36_21.geometry} material={materials._25} />
        <mesh name="Mesh36_22" geometry={nodes.Mesh36_22.geometry} material={materials._25_1} />
        <mesh name="Mesh36_23" geometry={nodes.Mesh36_23.geometry} material={materials._26} />
        <mesh name="Mesh36_24" geometry={nodes.Mesh36_24.geometry} material={materials._25_2} />
        <mesh name="Mesh36_25" geometry={nodes.Mesh36_25.geometry} material={materials._25_3} />
        <mesh name="Mesh36_26" geometry={nodes.Mesh36_26.geometry} material={materials._25_4} />
        <mesh name="Mesh36_27" geometry={nodes.Mesh36_27.geometry} material={materials._25_5} />
        <mesh name="Mesh36_28" geometry={nodes.Mesh36_28.geometry} material={materials._25_6} />
        <mesh name="Mesh36_29" geometry={nodes.Mesh36_29.geometry} material={materials._31} />
        <mesh name="Mesh36_30" geometry={nodes.Mesh36_30.geometry} material={materials._34} />
        <mesh name="Mesh36_31" geometry={nodes.Mesh36_31.geometry} material={materials._16_1} />
        <mesh name="Mesh36_32" geometry={nodes.Mesh36_32.geometry} material={materials._16_2} />
        <mesh name="Mesh36_33" geometry={nodes.Mesh36_33.geometry} material={materials._22} />
        <mesh name="Mesh36_34" geometry={nodes.Mesh36_34.geometry} material={materials._16_3} />
        <mesh name="Mesh36_35" geometry={nodes.Mesh36_35.geometry} material={materials._15_1} />
        <mesh name="Mesh36_36" geometry={nodes.Mesh36_36.geometry} material={materials._15_2} />
        <mesh name="Mesh36_37" geometry={nodes.Mesh36_37.geometry} material={materials._15_3} />
        <mesh name="Mesh36_38" geometry={nodes.Mesh36_38.geometry} material={materials._14} />
        <mesh name="Mesh36_39" geometry={nodes.Mesh36_39.geometry} material={materials._15_4} />
        <mesh name="Mesh36_40" geometry={nodes.Mesh36_40.geometry} material={materials._23} />
      </group>
      <mesh name="Mesh26" geometry={nodes.Mesh26.geometry} material={materials.Blinds_Cellular_White} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh76" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh76_1" geometry={nodes.Mesh76_1.geometry} material={materials._Asphalt_New_1} />
        <mesh name="Mesh76_2" geometry={nodes.Mesh76_2.geometry} material={materials.Blacktop_Old_02} />
      </group>
      <mesh name="Mesh39" geometry={nodes.Mesh39.geometry} material={materials.Metal_Aluminum_Anodized} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh50" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh50_1" geometry={nodes.Mesh50_1.geometry} material={materials.Vegetation_Grass_Artificial} />
        <mesh name="Mesh50_2" geometry={nodes.Mesh50_2.geometry} material={materials.Groundcover_Sand_Wind} />
      </group>
      <mesh name="Mesh46" geometry={nodes.Mesh46.geometry} material={materials.Fencing_Diamond_Mesh} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <group name="Mesh47" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh47_1" geometry={nodes.Mesh47_1.geometry} material={materials.Fencing_Construction} />
        <mesh name="Mesh47_2" geometry={nodes.Mesh47_2.geometry} material={materials._Fencing_Chain_Link_1} />
      </group>
      <group name="Mesh35" position={[-42.189, 0.44, -37.044]} scale={1.001}>
        <mesh name="Mesh35_1" geometry={nodes.Mesh35_1.geometry} material={materials._Grass_Light_Green_3} />
        <mesh name="Mesh35_2" geometry={nodes.Mesh35_2.geometry} material={materials.M_2897_1_} />
      </group>
      <group name="Mesh616" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh616_1" geometry={nodes.Mesh616_1.geometry} material={materials.Polished_Concrete_New1} />
        <mesh name="Mesh616_2" geometry={nodes.Mesh616_2.geometry} material={materials.Polished_Concrete_New2} />
        <mesh name="Mesh616_3" geometry={nodes.Mesh616_3.geometry} material={materials.Polished_Concrete_New3} />
        <mesh name="Mesh616_4" geometry={nodes.Mesh616_4.geometry} material={materials.Polished_Concrete_New4} />
        <mesh name="Mesh616_5" geometry={nodes.Mesh616_5.geometry} material={materials.Polished_Concrete_New5} />
        <mesh name="Mesh616_6" geometry={nodes.Mesh616_6.geometry} material={materials.Polished_Concrete_New6} />
        <mesh name="Mesh616_7" geometry={nodes.Mesh616_7.geometry} material={materials.Polished_Concrete_New7} />
        <mesh name="Mesh616_8" geometry={nodes.Mesh616_8.geometry} material={materials.Polished_Concrete_New8} />
        <mesh name="Mesh616_9" geometry={nodes.Mesh616_9.geometry} material={materials.Polished_Concrete_New9} />
        <mesh name="Mesh616_10" geometry={nodes.Mesh616_10.geometry} material={materials.Polished_Concrete_New10} />
        <mesh name="Mesh616_11" geometry={nodes.Mesh616_11.geometry} material={materials.Polished_Concrete_New11} />
        <mesh name="Mesh616_12" geometry={nodes.Mesh616_12.geometry} material={materials.Polished_Concrete_New12} />
      </group>
      <group name="Mesh626" position={[-42.189, 1.441, -37.044]} scale={1.001}>
        <mesh name="Mesh626_1" geometry={nodes.Mesh626_1.geometry} material={materials.M_166683_143419749050985_7434194_n} />
        <mesh name="Mesh626_2" geometry={nodes.Mesh626_2.geometry} material={materials.M_166683_143419749050985_7434194_n_4} />
        <mesh name="Mesh626_3" geometry={nodes.Mesh626_3.geometry} material={materials.M_166683_143419749050985_7434194_n_3} />
      </group>
      <mesh name="Mesh732" geometry={nodes.Mesh732.geometry} material={materials._Grass_Light_Green_2} position={[-42.189, 1.441, -37.044]} scale={1.001} />
      <mesh name="Mesh179" geometry={nodes.Mesh179.geometry} material={materials.Queensboro_Bridge_Tria} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh178" geometry={nodes.Mesh178.geometry} material={materials.Queensboro_Bridge_link} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh177" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh177_1" geometry={nodes.Mesh177_1.geometry} material={materials.Queensboro_Bridge_Top_railing} />
        <mesh name="Mesh177_2" geometry={nodes.Mesh177_2.geometry} material={materials.Queensboro_Bridge_Top_railing1} />
      </group>
      <group name="Mesh173" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh173_1" geometry={nodes.Mesh173_1.geometry} material={materials.Queensboro_Bridge_Tower_Top} />
        <mesh name="Mesh173_2" geometry={nodes.Mesh173_2.geometry} material={materials.Queensboro_Bridge_Road} />
      </group>
      <mesh name="Mesh62" geometry={nodes.Mesh62.geometry} material={materials.Queensboro_Bridge_Corner_Lever} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh1_1" geometry={nodes.Mesh1_1.geometry} material={materials.Queensboro_Bridge_Side_Lever} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh3" geometry={nodes.Mesh3.geometry} material={materials.Queensboro_Bridge_Center_Lever} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh7" geometry={nodes.Mesh7.geometry} material={materials.Diagnol} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh11_1" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh11_3" geometry={nodes.Mesh11_3.geometry} material={materials.Queensboro_Bridge_Side_Lever1} />
        <mesh name="Mesh11_4" geometry={nodes.Mesh11_4.geometry} material={materials.Queensboro_Bridge_Side_Lever2} />
      </group>
      <mesh name="Mesh12" geometry={nodes.Mesh12.geometry} material={materials.Queensboro_Bridge_Side_Lever3} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh14" geometry={nodes.Mesh14.geometry} material={materials.Queensboro_Bridge_Top} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh13" geometry={nodes.Mesh13.geometry} material={materials.Queensboro_Bridge_Pole} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh16" geometry={nodes.Mesh16.geometry} material={materials.Queensboro_Bridge_Arch} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh42" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh42_1" geometry={nodes.Mesh42_1.geometry} material={materials.Queensboro_Bridge_Pillar6} />
        <mesh name="Mesh42_2" geometry={nodes.Mesh42_2.geometry} material={materials.Queensboro_Bridge_Pillar10} />
        <mesh name="Mesh42_3" geometry={nodes.Mesh42_3.geometry} material={materials.Queensboro_Bridge_Pillar} />
        <mesh name="Mesh42_4" geometry={nodes.Mesh42_4.geometry} material={materials.Queensboro_Bridge_Pillar1} />
        <mesh name="Mesh42_5" geometry={nodes.Mesh42_5.geometry} material={materials.Queensboro_Bridge_Pillar2} />
        <mesh name="Mesh42_6" geometry={nodes.Mesh42_6.geometry} material={materials.Queensboro_Bridge_Pillar3} />
        <mesh name="Mesh42_7" geometry={nodes.Mesh42_7.geometry} material={materials.Queensboro_Bridge_Pillar4} />
        <mesh name="Mesh42_8" geometry={nodes.Mesh42_8.geometry} material={materials.Queensboro_Bridge_Pillar5} />
        <mesh name="Mesh42_9" geometry={nodes.Mesh42_9.geometry} material={materials.Queensboro_Bridge_Pillar7} />
        <mesh name="Mesh42_10" geometry={nodes.Mesh42_10.geometry} material={materials.Queensboro_Bridge_Pillar8} />
        <mesh name="Mesh42_11" geometry={nodes.Mesh42_11.geometry} material={materials.Queensboro_Bridge_Pillar9} />
        <mesh name="Mesh42_12" geometry={nodes.Mesh42_12.geometry} material={materials.Queensboro_Bridge_Pillar11} />
        <mesh name="Mesh42_13" geometry={nodes.Mesh42_13.geometry} material={materials.Queensboro_Bridge_Pillar12} />
        <mesh name="Mesh42_14" geometry={nodes.Mesh42_14.geometry} material={materials.Queensboro_Bridge_Pillar13} />
        <mesh name="Mesh42_15" geometry={nodes.Mesh42_15.geometry} material={materials.Queensboro_Bridge_Pillar14} />
        <mesh name="Mesh42_16" geometry={nodes.Mesh42_16.geometry} material={materials.Queensboro_Bridge_Pillar15} />
        <mesh name="Mesh42_17" geometry={nodes.Mesh42_17.geometry} material={materials.Queensboro_Bridge_Pillar16} />
      </group>
      <group name="Mesh58" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh58_1" geometry={nodes.Mesh58_1.geometry} material={materials.Queensboro_Bridge_Pillar17} />
        <mesh name="Mesh58_2" geometry={nodes.Mesh58_2.geometry} material={materials.Queensboro_Bridge_Pillar18} />
      </group>
      <mesh name="Mesh59" geometry={nodes.Mesh59.geometry} material={materials.Queensboro_Bridge_Side_Lever4} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh203" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh203_1" geometry={nodes.Mesh203_1.geometry} material={materials.Queensboro_Bridge_Railing} />
        <mesh name="Mesh203_2" geometry={nodes.Mesh203_2.geometry} material={materials.Queensboro_Bridge_Pillar19} />
        <mesh name="Mesh203_3" geometry={nodes.Mesh203_3.geometry} material={materials.Queensboro_Bridge_Pillar20} />
        <mesh name="Mesh203_4" geometry={nodes.Mesh203_4.geometry} material={materials.Queensboro_Bridge_Pillar21} />
        <mesh name="Mesh203_5" geometry={nodes.Mesh203_5.geometry} material={materials.Queensboro_Bridge_Pillar22} />
        <mesh name="Mesh203_6" geometry={nodes.Mesh203_6.geometry} material={materials.Queensboro_Bridge_Pillar23} />
        <mesh name="Mesh203_7" geometry={nodes.Mesh203_7.geometry} material={materials.Queensboro_Bridge_Pillar24} />
        <mesh name="Mesh203_8" geometry={nodes.Mesh203_8.geometry} material={materials.Queensboro_Bridge_Pillar25} />
        <mesh name="Mesh203_9" geometry={nodes.Mesh203_9.geometry} material={materials.Queensboro_Bridge_Pillar26} />
        <mesh name="Mesh203_10" geometry={nodes.Mesh203_10.geometry} material={materials.Queensboro_Bridge_Pillar27} />
        <mesh name="Mesh203_11" geometry={nodes.Mesh203_11.geometry} material={materials.Queensboro_Bridge_Pillar28} />
        <mesh name="Mesh203_12" geometry={nodes.Mesh203_12.geometry} material={materials.Queensboro_Bridge_Pillar29} />
        <mesh name="Mesh203_13" geometry={nodes.Mesh203_13.geometry} material={materials.Queensboro_Bridge_Pillar30} />
        <mesh name="Mesh203_14" geometry={nodes.Mesh203_14.geometry} material={materials.Queensboro_Bridge_Pillar31} />
        <mesh name="Mesh203_15" geometry={nodes.Mesh203_15.geometry} material={materials.Queensboro_Bridge_Pillar32} />
        <mesh name="Mesh203_16" geometry={nodes.Mesh203_16.geometry} material={materials.Queensboro_Bridge_Pillar33} />
        <mesh name="Mesh203_17" geometry={nodes.Mesh203_17.geometry} material={materials.Queensboro_Bridge_Pillar34} />
        <mesh name="Mesh203_18" geometry={nodes.Mesh203_18.geometry} material={materials.Queensboro_Bridge_Pillar35} />
        <mesh name="Mesh203_19" geometry={nodes.Mesh203_19.geometry} material={materials.Queensboro_Bridge_Pillar36} />
        <mesh name="Mesh203_20" geometry={nodes.Mesh203_20.geometry} material={materials.Queensboro_Bridge_Pillar37} />
        <mesh name="Mesh203_21" geometry={nodes.Mesh203_21.geometry} material={materials.Queensboro_Bridge_Pillar39} />
        <mesh name="Mesh203_22" geometry={nodes.Mesh203_22.geometry} material={materials.Queensboro_Bridge_Pillar40} />
        <mesh name="Mesh203_23" geometry={nodes.Mesh203_23.geometry} material={materials.Queensboro_Bridge_Pillar41} />
        <mesh name="Mesh203_24" geometry={nodes.Mesh203_24.geometry} material={materials.Queensboro_Bridge_Pillar42} />
        <mesh name="Mesh203_25" geometry={nodes.Mesh203_25.geometry} material={materials.Queensboro_Bridge_Pillar43} />
        <mesh name="Mesh203_26" geometry={nodes.Mesh203_26.geometry} material={materials.Queensboro_Bridge_Pillar44} />
        <mesh name="Mesh203_27" geometry={nodes.Mesh203_27.geometry} material={materials.Queensboro_Bridge_Pillar45} />
        <mesh name="Mesh203_28" geometry={nodes.Mesh203_28.geometry} material={materials.Queensboro_Bridge_Pillar46} />
        <mesh name="Mesh203_29" geometry={nodes.Mesh203_29.geometry} material={materials.Queensboro_Bridge_Pillar47} />
        <mesh name="Mesh203_30" geometry={nodes.Mesh203_30.geometry} material={materials.Queensboro_Bridge_Pillar48} />
        <mesh name="Mesh203_31" geometry={nodes.Mesh203_31.geometry} material={materials.Queensboro_Bridge_Pillar49} />
        <mesh name="Mesh203_32" geometry={nodes.Mesh203_32.geometry} material={materials.Queensboro_Bridge_Pillar50} />
        <mesh name="Mesh203_33" geometry={nodes.Mesh203_33.geometry} material={materials.Queensboro_Bridge_Pillar51} />
        <mesh name="Mesh203_34" geometry={nodes.Mesh203_34.geometry} material={materials.Queensboro_Bridge_Pillar52} />
        <mesh name="Mesh203_35" geometry={nodes.Mesh203_35.geometry} material={materials.Queensboro_Bridge_Pillar53} />
        <mesh name="Mesh203_36" geometry={nodes.Mesh203_36.geometry} material={materials.Queensboro_Bridge_Pillar54} />
        <mesh name="Mesh203_37" geometry={nodes.Mesh203_37.geometry} material={materials.Queensboro_Bridge_Pillar55} />
        <mesh name="Mesh203_38" geometry={nodes.Mesh203_38.geometry} material={materials.Queensboro_Bridge_Pillar56} />
        <mesh name="Mesh203_39" geometry={nodes.Mesh203_39.geometry} material={materials.Queensboro_Bridge_Pillar57} />
        <mesh name="Mesh203_40" geometry={nodes.Mesh203_40.geometry} material={materials.Queensboro_Bridge_Pillar58} />
        <mesh name="Mesh203_41" geometry={nodes.Mesh203_41.geometry} material={materials.Queensboro_Bridge_Pillar60} />
        <mesh name="Mesh203_42" geometry={nodes.Mesh203_42.geometry} material={materials.Queensboro_Bridge_Pillar61} />
        <mesh name="Mesh203_43" geometry={nodes.Mesh203_43.geometry} material={materials.Queensboro_Bridge_Pillar62} />
        <mesh name="Mesh203_44" geometry={nodes.Mesh203_44.geometry} material={materials.Queensboro_Bridge_Pillar63} />
        <mesh name="Mesh203_45" geometry={nodes.Mesh203_45.geometry} material={materials.Queensboro_Bridge_Pillar64} />
        <mesh name="Mesh203_46" geometry={nodes.Mesh203_46.geometry} material={materials.Queensboro_Bridge_Pillar65} />
        <mesh name="Mesh203_47" geometry={nodes.Mesh203_47.geometry} material={materials.Queensboro_Bridge_Pillar66} />
        <mesh name="Mesh203_48" geometry={nodes.Mesh203_48.geometry} material={materials.Queensboro_Bridge_Pillar67} />
        <mesh name="Mesh203_49" geometry={nodes.Mesh203_49.geometry} material={materials.Queensboro_Bridge_Pillar68} />
        <mesh name="Mesh203_50" geometry={nodes.Mesh203_50.geometry} material={materials.Queensboro_Bridge_Pillar69} />
        <mesh name="Mesh203_51" geometry={nodes.Mesh203_51.geometry} material={materials.Queensboro_Bridge_Pillar70} />
        <mesh name="Mesh203_52" geometry={nodes.Mesh203_52.geometry} material={materials.Queensboro_Bridge_Pillar71} />
        <mesh name="Mesh203_53" geometry={nodes.Mesh203_53.geometry} material={materials.Queensboro_Bridge_Pillar72} />
        <mesh name="Mesh203_54" geometry={nodes.Mesh203_54.geometry} material={materials.Queensboro_Bridge_Pillar73} />
        <mesh name="Mesh203_55" geometry={nodes.Mesh203_55.geometry} material={materials.Queensboro_Bridge_Pillar74} />
        <mesh name="Mesh203_56" geometry={nodes.Mesh203_56.geometry} material={materials.Queensboro_Bridge_Pillar75} />
        <mesh name="Mesh203_57" geometry={nodes.Mesh203_57.geometry} material={materials.Queensboro_Bridge_Pillar76} />
        <mesh name="Mesh203_58" geometry={nodes.Mesh203_58.geometry} material={materials.Queensboro_Bridge_Pillar77} />
        <mesh name="Mesh203_59" geometry={nodes.Mesh203_59.geometry} material={materials.Queensboro_Bridge_Pillar78} />
        <mesh name="Mesh203_60" geometry={nodes.Mesh203_60.geometry} material={materials.Queensboro_Bridge_Pillar79} />
        <mesh name="Mesh203_61" geometry={nodes.Mesh203_61.geometry} material={materials.Queensboro_Bridge_Pillar80} />
        <mesh name="Mesh203_62" geometry={nodes.Mesh203_62.geometry} material={materials.Queensboro_Bridge_Pillar81} />
        <mesh name="Mesh203_63" geometry={nodes.Mesh203_63.geometry} material={materials.Queensboro_Bridge_Pillar82} />
        <mesh name="Mesh203_64" geometry={nodes.Mesh203_64.geometry} material={materials.Queensboro_Bridge_Pillar38} />
      </group>
      <mesh name="Mesh60" geometry={nodes.Mesh60.geometry} material={materials.Queensboro_Bridge_Middle_Lever} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh224" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh224_1" geometry={nodes.Mesh224_1.geometry} material={materials.car_side} />
        <mesh name="Mesh224_2" geometry={nodes.Mesh224_2.geometry} material={materials.car_side1} />
        <mesh name="Mesh224_3" geometry={nodes.Mesh224_3.geometry} material={materials.Kugel_Silver_Uffizi1} />
        <mesh name="Mesh224_4" geometry={nodes.Mesh224_4.geometry} material={materials.car_north} />
        <mesh name="Mesh224_5" geometry={nodes.Mesh224_5.geometry} material={materials.car_north_2} />
        <mesh name="Mesh224_6" geometry={nodes.Mesh224_6.geometry} material={materials.car_north_3} />
        <mesh name="Mesh224_7" geometry={nodes.Mesh224_7.geometry} material={materials.red_carpaint_png2f94dec3_1426_4fda_b73b_36dcd8d82b71Larger} />
        <mesh name="Mesh224_8" geometry={nodes.Mesh224_8.geometry} material={materials.car_north_3_1} />
        <mesh name="Mesh224_9" geometry={nodes.Mesh224_9.geometry} material={materials.car_north_2_1} />
        <mesh name="Mesh224_10" geometry={nodes.Mesh224_10.geometry} material={materials.car_north1} />
      </group>
      <group name="Mesh222" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh222_1" geometry={nodes.Mesh222_1.geometry} material={materials.car_swing} />
        <mesh name="Mesh222_2" geometry={nodes.Mesh222_2.geometry} material={materials.Metallic_Silver} />
        <mesh name="Mesh222_3" geometry={nodes.Mesh222_3.geometry} material={materials.car_swing2} />
      </group>
      <group name="Mesh223" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh223_1" geometry={nodes.Mesh223_1.geometry} material={materials.rail} />
        <mesh name="Mesh223_2" geometry={nodes.Mesh223_2.geometry} material={materials.car_cable_clamp} />
        <mesh name="Mesh223_3" geometry={nodes.Mesh223_3.geometry} material={materials.car_cable_clamp1} />
      </group>
      <group name="Mesh204" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh204_1" geometry={nodes.Mesh204_1.geometry} material={materials.tower_center_base} />
        <mesh name="Mesh204_2" geometry={nodes.Mesh204_2.geometry} material={materials.RI_lattice_tower_NS___upper_shell} />
        <mesh name="Mesh204_3" geometry={nodes.Mesh204_3.geometry} material={materials.RI_lattice_tower_NS___upper_shell1} />
        <mesh name="Mesh204_4" geometry={nodes.Mesh204_4.geometry} material={materials.RI_lattice_tower_east___upper_shell} />
        <mesh name="Mesh204_5" geometry={nodes.Mesh204_5.geometry} material={materials.tower_center_base1} />
        <mesh name="Mesh204_6" geometry={nodes.Mesh204_6.geometry} material={materials.ri_tower_center_ew} />
        <mesh name="Mesh204_7" geometry={nodes.Mesh204_7.geometry} material={materials.RI_lattice_tower_NS___upper_shell2} />
        <mesh name="Mesh204_8" geometry={nodes.Mesh204_8.geometry} material={materials.RI_lattice_tower_NS___upper_shell3} />
        <mesh name="Mesh204_9" geometry={nodes.Mesh204_9.geometry} material={materials.RI_lattice_tower_NS___upper_shell4} />
        <mesh name="Mesh204_10" geometry={nodes.Mesh204_10.geometry} material={materials.ri_tower_center_ew1} />
        <mesh name="Mesh204_11" geometry={nodes.Mesh204_11.geometry} material={materials.RI_lattice_tower_NS___upper_shell5} />
        <mesh name="Mesh204_12" geometry={nodes.Mesh204_12.geometry} material={materials.RI_lattice_tower_east___upper_shell1} />
      </group>
      <mesh name="Mesh205" geometry={nodes.Mesh205.geometry} material={materials.cable} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh209" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh209_1" geometry={nodes.Mesh209_1.geometry} material={materials.M_3231936245_84b46d05a7} />
        <mesh name="Mesh209_2" geometry={nodes.Mesh209_2.geometry} material={materials.ri_tower_crown} />
        <mesh name="Mesh209_3" geometry={nodes.Mesh209_3.geometry} material={materials.ri_tower_crown2} />
        <mesh name="Mesh209_4" geometry={nodes.Mesh209_4.geometry} material={materials.ri_tower_crown2_1} />
        <mesh name="Mesh209_5" geometry={nodes.Mesh209_5.geometry} material={materials.ri_tower_crown2_2} />
        <mesh name="Mesh209_6" geometry={nodes.Mesh209_6.geometry} material={materials.ri_tower_crown2_3} />
        <mesh name="Mesh209_7" geometry={nodes.Mesh209_7.geometry} material={materials.ri_tower_crown2_4} />
      </group>
      <mesh name="Mesh207" geometry={nodes.Mesh207.geometry} material={materials.rail_brace} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh210" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh210_1" geometry={nodes.Mesh210_1.geometry} material={materials.Kugel_Silver_Uffizi} />
        <mesh name="Mesh210_2" geometry={nodes.Mesh210_2.geometry} material={materials.tower_rail} />
      </group>
      <mesh name="Mesh214" geometry={nodes.Mesh214.geometry} material={materials.tower_roller} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh218" geometry={nodes.Mesh218.geometry} material={materials.roller_rail1} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <mesh name="Mesh216" geometry={nodes.Mesh216.geometry} material={materials.roller_rail} position={[-42.189, 1.646, -37.25]} scale={100.073} />
      <group name="Mesh294_1" position={[-42.189, 1.646, -37.25]} scale={100.073}>
        <mesh name="Mesh294_4" geometry={nodes.Mesh294_4.geometry} material={materials.RI_lattice_tower_NS___upper_shell6} />
        <mesh name="Mesh294_5" geometry={nodes.Mesh294_5.geometry} material={materials.RI_lattice_tower_east___upper_shell2} />
        <mesh name="Mesh294_6" geometry={nodes.Mesh294_6.geometry} material={materials.RI_lattice_tower_east___upper_shell3} />
        <mesh name="Mesh294_7" geometry={nodes.Mesh294_7.geometry} material={materials.RI_lattice_tower_NS___upper_shell7} />
        <mesh name="Mesh294_8" geometry={nodes.Mesh294_8.geometry} material={materials.RI_lattice_tower_NS___lower_shell} />
        <mesh name="Mesh294_9" geometry={nodes.Mesh294_9.geometry} material={materials.RI_lattice_tower_east___lower_shell} />
        <mesh name="Mesh294_10" geometry={nodes.Mesh294_10.geometry} material={materials.RI_lattice_tower_NS___lower_shell1} />
        <mesh name="Mesh294_11" geometry={nodes.Mesh294_11.geometry} material={materials.RI_lattice_tower_east___lower_shell1} />
        <mesh name="Mesh294_12" geometry={nodes.Mesh294_12.geometry} material={materials.RI_lattice_tower_NS___upper_shell8} />
        <mesh name="Mesh294_13" geometry={nodes.Mesh294_13.geometry} material={materials.RI_lattice_tower_east___upper_shell4} />
        <mesh name="Mesh294_14" geometry={nodes.Mesh294_14.geometry} material={materials.RI_lattice_tower_NS___upper_shell9} />
        <mesh name="Mesh294_15" geometry={nodes.Mesh294_15.geometry} material={materials.RI_lattice_tower_east___lower_shell2} />
        <mesh name="Mesh294_16" geometry={nodes.Mesh294_16.geometry} material={materials.RI_lattice_tower_NS___lower_shell2} />
        <mesh name="Mesh294_17" geometry={nodes.Mesh294_17.geometry} material={materials.RI_lattice_tower_east___lower_shell3} />
        <mesh name="Mesh294_18" geometry={nodes.Mesh294_18.geometry} material={materials.RI_lattice_tower_NS___lower_shell3} />
      </group>
      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Custom} position={[-41.633, -275.813, 353.667]} scale={100.073} />
      <mesh name="Object_1_5" geometry={nodes.Object_1_5.geometry} material={materials.Plastic} position={[-41.633, -275.813, 353.667]} scale={100.073} />
      <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial003} position={[-41.633, -275.813, 353.667]} scale={100.073} />
      <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Blinds_Roman_Hobbled_Blue} position={[-41.633, -275.813, 353.667]} scale={100.073} />
      <mesh name="Mesh4_1" geometry={nodes.Mesh4_1.geometry} material={materials.Polished_Concrete_Old} position={[-34.163, -277.748, 352.947]} scale={100.073} />
      <mesh name="Mesh25_3" geometry={nodes.Mesh25_3.geometry} material={materials.FDNY} position={[-34.163, -277.748, 352.947]} scale={100.073} />
      <mesh name="Mesh4_4" geometry={nodes.Mesh4_4.geometry} material={materials.Fire2} position={[-34.163, -277.748, 352.947]} scale={100.073} />
      <mesh name="Mesh4_3" geometry={nodes.Mesh4_3.geometry} material={materials.Fire3} position={[-34.163, -277.748, 352.947]} scale={100.073} />
      <mesh name="Mesh4_2" geometry={nodes.Mesh4_2.geometry} material={materials.Fire4} position={[-34.163, -277.748, 352.947]} scale={100.073} />
      <mesh name="Mesh25_2" geometry={nodes.Mesh25_2.geometry} material={materials.FireWall} position={[-34.163, -277.748, 352.947]} scale={100.073} />
      <mesh name="Mesh25_1" geometry={nodes.Mesh25_1.geometry} material={materials.M_531c} position={[-34.163, -277.748, 352.947]} scale={100.073} />
    </group>
  )
}

useGLTF.preload('/RI_TemplateScene-transformed.glb')
