/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Mercedes-Benz_E63.gltf --transform 
Files: Mercedes-Benz_E63.gltf [15.83KB] > /Users/hgs52/Downloads/RI/mercedes/Mercedes-Benz_E63-transformed.glb [87.46KB] (-452%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('/Mercedes-Benz_E63-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0,0,0]} rotation={[0.001, -0.594, 0.001]} scale={0.031}>
        <mesh geometry={nodes['Mercedes-Benz_E63_(1)_2'].geometry} material={materials.Glass} />
        <mesh geometry={nodes['Mercedes-Benz_E63_(1)_3'].geometry} material={materials['Glass Light']} />
        <mesh geometry={nodes['Mercedes-Benz_E63_(1)_4'].geometry} material={materials['Textures 1']} />
      </group>
      {/* <mesh geometry={nodes.Wheel_BL.geometry} material={materials['Tex tures Wheel']} position={[0.0,0.0, 0.0]} rotation={[0.001, 0.0, 0.0]} scale={0.1} /> */}
    </group>
  )
}

useGLTF.preload('/Mercedes-Benz_E63-transformed.glb')
