/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 RI_TemplateScene.gltf --transform 
Files: RI_TemplateScene.gltf [2.9MB] > /Users/hgs52/Downloads/RI/RI/RI_TemplateScene-transformed.glb [5.73MB] (-98%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/RI_TemplateScene-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  
  return (
    <group {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload('/RI_TemplateScene-transformed.glb')
