/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 RI_TemplateScene.gltf --transform 
Files: RI_TemplateScene.gltf [4.18MB] > /Users/hgs52/Downloads/RI/Island/RI_TemplateScene-transformed.glb [7.63MB] (-82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model({ hiddenMeshes = [], ...props }) {
  const { scene } = useGLTF('/RI_TemplateScene.glb')
  const clone = React.useMemo(() => {
    const clonedScene = SkeletonUtils.clone(scene)
    
    // Hide specified meshes
    if (hiddenMeshes.length > 0) {
      clonedScene.traverse((node) => {
        if (node.isMesh && hiddenMeshes.includes(node.name)) {
          node.visible = false
        }
      })
    }
    
    return clonedScene
  }, [scene, hiddenMeshes])

  return (
    <group {...props} dispose={null}>
      <primitive object={clone} />
    </group>
  )
}

useGLTF.preload('/RI_TemplateScene-transformed.glb')
